# Generated by Django 4.2.16 on 2024-12-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophop', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
