# Generated by Django 4.2.16 on 2024-12-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shophop", "0004_rename_name_product_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="standardized_quantity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
