# Generated by Django 4.2.16 on 2024-12-04 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophop', '0005_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheapProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('standardized_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('store', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
