# Generated by Django 4.2.16 on 2024-12-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophop', '0006_cheapproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheapproducts',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='cheapproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cheapproducts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cheapproducts',
            name='standardized_quantity',
        ),
        migrations.RemoveField(
            model_name='cheapproducts',
            name='store',
        ),
    ]
